version: '3'

services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'teamsoft'
    restart: always
    volumes:
      - teamsoft-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: admin

volumes:
  teamsoft-data: